### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Mackingzie** [jwilsson/spotify-web-api-php#112]
Hi!
I'm having an issue with CORS. Using your code . 
Issue:
Failed to load https://accounts.spotify.com/authorize/?client_id=[id]&redirect_uri=http%3A%2F%2F[my ip]&response_type=code&scope=user-read-email&state=0: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://[my ip]' is therefore not allowed access.

**Comment by jwilsson** [comment]
Hi!
This doesn’t sound like an issue with this library since it never interacts with the browser.

I’m guessing you’ve got some client-side JavaScript which is trying to request the Spotify API and thus failing the CORS Check from your browser.

I’m going to close this since it’s not related to this library, but pleas give me a shout if you think it should be reopened!

**Comment by andersborgabiro** [comment]
Do you lack '<access origin="*" />' (or similar)?
