### ISSUE TITLE
Error: Forbidden Your client does not have permission to get URL /v1/me/player/recently-played/ from this server.

### ISSUE THREAD

**Issue by StefSchalks** [jwilsson/spotify-web-api-php#261]
Hi,
I'm getting the following error while making requests using this package:
`Your client does not have permission to get URL /v1/me/player/recently-played/ from this server.`

My tokens are refreshing and the access tokens are valid.
Does anyone know what could be the problem?

Kind Regards,
Stef

**Comment by jwilsson** [comment]
Hey!
I've seen this issue before and that time it solved itself after a few days. I think it's related to the IP you're connecting from being blocked by Google (Spotify uses GCP), have you tried from a different network/server?

**Comment by Xemaro** [comment]
Same problem here, since two weeks approximately. I checked with two different computers and my smartphone, on many days and with different networks (Wi-Fi, 4g, even with and without a VPN), I even tried to rotate my client secret, nothing seems to change.
I can bring a new information : it seems to be random, in some cases the request works and gives back the answer (for example, for the `/me/tracks` request, I sometimes receive the forbidden error when the `limit` endpoint is at `50`, sometimes `250`, etc. (the highest I reached was `600)`.
